/// <reference path="./node-shims.d.ts" />

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createRender2DPrepare } from "../../src/cluster/engine/services/render/modules/Render2DPrepare.module";
import { createRender2DUpload } from "../../src/cluster/engine/services/render/modules/Render2DUpload.module";
import {
    createRenderProfileScenarios,
    type RenderProfileScenario,
} from "./scenarios";
import { summarizeTimingSeries, type TimingSummary } from "./summary";

export const RENDER_PROFILE_WARMUP_FRAMES = 30;
export const RENDER_PROFILE_SAMPLE_FRAMES = 120;

type RenderProfileStats = Readonly<{
    commandCount: number;
    batchCount: number;
    vertexCount: number;
    uploadByteLength: number;
    uploadFloatLength: number;
    rangeCount: number;
    layoutUploadCount: number;
}>;

export type RenderProfileScenarioResult = Readonly<{
    profileVersion: 1;
    scenario: string;
    itemCount: number;
    warmupFrames: number;
    sampleFrames: number;
    frameCpuMs: TimingSummary;
    prepareMs: TimingSummary;
    uploadBuildMs: TimingSummary;
    submitCpuMs: TimingSummary;
    totalCpuMs: TimingSummary;
    stats: RenderProfileStats;
}>;

export type RenderProfileSummary = Readonly<{
    profileVersion: 1;
    commandUsed: string;
    warmupFrames: number;
    sampleFrames: number;
    scenarios: readonly RenderProfileScenarioResult[];
}>;

type MutableTimingSamples = {
    frameCpuMs: number[];
    prepareMs: number[];
    uploadBuildMs: number[];
    submitCpuMs: number[];
};

function createTimingSamples(): MutableTimingSamples {
    return {
        frameCpuMs: [],
        prepareMs: [],
        uploadBuildMs: [],
        submitCpuMs: [],
    };
}

function roundTiming(summary: TimingSummary): TimingSummary {
    return {
        min: Number(summary.min.toFixed(4)),
        median: Number(summary.median.toFixed(4)),
        p95: Number(summary.p95.toFixed(4)),
        mean: Number(summary.mean.toFixed(4)),
    };
}

function measureScenario(
    scenario: RenderProfileScenario,
): RenderProfileScenarioResult {
    const prepare = createRender2DPrepare();
    const upload = createRender2DUpload();
    const samples = createTimingSamples();
    let stats: RenderProfileStats = {
        commandCount: 0,
        batchCount: 0,
        vertexCount: 0,
        uploadByteLength: 0,
        uploadFloatLength: 0,
        rangeCount: 0,
        layoutUploadCount: 0,
    };

    for (
        let frameIndex = 0;
        frameIndex < RENDER_PROFILE_WARMUP_FRAMES + RENDER_PROFILE_SAMPLE_FRAMES;
        frameIndex++
    ) {
        const isSample = frameIndex >= RENDER_PROFILE_WARMUP_FRAMES;
        const frameStart = globalThis.performance.now();
        const prepareStart = globalThis.performance.now();
        const preparedFrame = prepare.prepare(scenario.input);
        const prepareEnd = globalThis.performance.now();
        const uploadStart = globalThis.performance.now();
        const uploadFrame = upload.build(preparedFrame);
        const uploadEnd = globalThis.performance.now();
        const submitCpuMs = 0;
        const frameEnd = globalThis.performance.now();

        stats = {
            commandCount: preparedFrame.stats.commandCount,
            batchCount: preparedFrame.stats.batchCount,
            vertexCount: preparedFrame.stats.vertexCount,
            uploadByteLength: uploadFrame.stats.uploadByteLength,
            uploadFloatLength: uploadFrame.stats.uploadFloatLength,
            rangeCount: uploadFrame.stats.rangeCount,
            layoutUploadCount: uploadFrame.stats.layoutUploadCount,
        };

        if (!isSample) continue;

        samples.frameCpuMs.push(frameEnd - frameStart);
        samples.prepareMs.push(prepareEnd - prepareStart);
        samples.uploadBuildMs.push(uploadEnd - uploadStart);
        samples.submitCpuMs.push(submitCpuMs);
    }

    const frameCpuMs = roundTiming(summarizeTimingSeries(samples.frameCpuMs));

    return {
        profileVersion: 1,
        scenario: scenario.name,
        itemCount: scenario.itemCount,
        warmupFrames: RENDER_PROFILE_WARMUP_FRAMES,
        sampleFrames: RENDER_PROFILE_SAMPLE_FRAMES,
        frameCpuMs,
        prepareMs: roundTiming(summarizeTimingSeries(samples.prepareMs)),
        uploadBuildMs: roundTiming(summarizeTimingSeries(samples.uploadBuildMs)),
        submitCpuMs: roundTiming(summarizeTimingSeries(samples.submitCpuMs)),
        totalCpuMs: frameCpuMs,
        stats,
    };
}

function createReadme(commandUsed: string): string {
    return [
        "# Render Profile Current Baseline",
        "",
        "Generated by the Phase 00a CPU-side renderer profiling harness.",
        "",
        `Command: \`${commandUsed}\``,
        "",
        "- No browser, canvas, WebGL2, or WebGPU context is required.",
        "- `submitCpuMs` is zero because this baseline does not include a backend-free fake submit path.",
        "- Scenario JSON files and `summary.json` are written in this directory.",
        "",
    ].join("\n");
}

export async function runRenderProfile(options: {
    outputDir?: string;
    commandUsed?: string;
} = {}): Promise<RenderProfileSummary> {
    const outputDir =
        options.outputDir ?? join(process.cwd(), ".artifacts", "render-profile", "current");
    const commandUsed = options.commandUsed ?? "npm.cmd run profile:render";
    const scenarios = createRenderProfileScenarios();
    const results = scenarios.map(measureScenario);
    const summary: RenderProfileSummary = {
        profileVersion: 1,
        commandUsed,
        warmupFrames: RENDER_PROFILE_WARMUP_FRAMES,
        sampleFrames: RENDER_PROFILE_SAMPLE_FRAMES,
        scenarios: results,
    };

    await mkdir(outputDir, { recursive: true });
    await Promise.all(
        results.map((result) =>
            writeFile(
                join(outputDir, `${result.scenario}.json`),
                `${JSON.stringify(result, null, 2)}\n`,
                "utf8",
            ),
        ),
    );
    await writeFile(
        join(outputDir, "summary.json"),
        `${JSON.stringify(summary, null, 2)}\n`,
        "utf8",
    );
    await writeFile(join(outputDir, "README.md"), createReadme(commandUsed), "utf8");

    return summary;
}
